"""AESAN recognised natural mineral waters — generated snapshot.

Do not edit by hand — regenerate with:
    python3 packages/be_water/scripts/refresh_aesan_snapshot.py
A git diff here means AESAN recognised (or dropped) waters.
"""

AESAN_VERSION = "AMN/08"
AESAN_DATE = "17/09/2018"

AESAN_WATERS = [
    {
        "name": "Abelleira",
        "spring": "Abelleira",
        "place": "Cospeito",
        "province": "Lugo",
    },
    {
        "name": "Agua de Albarcin",
        "spring": "Albarcin",
        "place": "Guadix",
        "province": "Granada",
    },
    {
        "name": "Agua de Bejís",
        "spring": "Los Cloticos",
        "place": "Bejís",
        "province": "Castellón",
    },
    {
        "name": "Agua de Bronchales",
        "spring": "Bronchales-3",
        "place": "Bronchales",
        "province": "Teruel",
    },
    {
        "name": "Agua de Bronchales",
        "spring": "Bronchales-5",
        "place": "Bronchales",
        "province": "Teruel",
    },
    {
        "name": "Agua de Chovar",
        "spring": "Manantial Chóvar",
        "place": "Chovar",
        "province": "Castellón",
    },
    {
        "name": "Agua de Cuevas",
        "spring": "Fuente de Cuevas",
        "place": "Aller",
        "province": "Asturias",
    },
    {
        "name": "Agua de Quess",
        "spring": "Manantial de Quess",
        "place": "Quess-Piloña",
        "province": "Asturias",
    },
    {
        "name": "Agua de Sousas",
        "spring": "Sousas II",
        "place": "Verín",
        "province": "Ourense",
    },
    {
        "name": "Agua de Teror",
        "spring": "Fuente Agria de Teror",
        "place": "Teror",
        "province": "Las Palmas",
    },
    {
        "name": "Agua del Rosal",
        "spring": "Agua del Rosal",
        "place": "Calera y Chozas",
        "province": "Toledo",
    },
    {
        "name": "Agua Encaja Mejor",
        "spring": "Castillo de Gormaz",
        "place": "Gormaz",
        "province": "Soria",
    },
    {
        "name": "Aguadoy",
        "spring": "Aguadoy",
        "place": "Calera y Chozas",
        "province": "Toledo",
    },
    {
        "name": "Aguas de la Palma",
        "spring": "Barbuzano Santa Cruz de la Palma",
        "place": "",
        "province": "Santa Cruz de Tenerife",
    },
    {
        "name": "Aguas de Manzanera",
        "spring": "El Salvador",
        "place": "Manzanera",
        "province": "Teruel",
    },
    {
        "name": "Aguas de Ribagorza",
        "spring": "Ribagorza",
        "place": "Graus",
        "province": "Huesca",
    },
    {
        "name": "Aguas do Paraño",
        "spring": "Captación Paraño 87.1",
        "place": "Boborás",
        "province": "Ourense",
    },
    {
        "name": "Aguasana",
        "spring": "A Granxa/La Granja",
        "place": "Belesar-Baiona",
        "province": "Pontevedra",
    },
    {
        "name": "Aigua de Ribes",
        "spring": "Fontaga",
        "place": "Ribes de Freser",
        "province": "Girona",
    },
    {
        "name": "Aigua de Vilajuïga",
        "spring": "Vilajuïga",
        "place": "Vilajuïga",
        "province": "Girona",
    },
    {
        "name": "Aigua del Montseny",
        "spring": "Aigua del Montseny",
        "place": "Sant Esteve de Palautordera",
        "province": "Barcelona",
    },
    {
        "name": "Aiguaneu",
        "spring": "Aiguaneu",
        "place": "Espinelves",
        "province": "Girona",
    },
    {
        "name": "Alzola",
        "spring": "Alzola",
        "place": "Alzola-Elgoibar",
        "province": "Guipúzcoa",
    },
    {
        "name": "Aqua Nevada",
        "spring": "Aqua Nevada",
        "place": "El Tesorillo, Albuñán",
        "province": "Granada",
    },
    {
        "name": "Aquabona Fontoira",
        "spring": "Fontoira",
        "place": "Cospeito",
        "province": "Lugo",
    },
    {
        "name": "Aquabona Fuen- Mayor",
        "spring": "Fuen-Mayor",
        "place": "Cañizar del Olivar",
        "province": "Teruel",
    },
    {
        "name": "Aquabona Peña Umbría",
        "spring": "Peña Umbría",
        "place": "Requena",
        "province": "Valencia",
    },
    {
        "name": "Aquabona Santolín",
        "spring": "Santolín",
        "place": "Quintanaurria",
        "province": "Burgos",
    },
    {
        "name": "Aquadeus",
        "spring": "Fuente Arquillo",
        "place": "El Robledo",
        "province": "Albacete",
    },
    {
        "name": "Aquadomus",
        "spring": "Aquadomus",
        "place": "Saldaña",
        "province": "Palencia",
    },
    {
        "name": "Aquarel",
        "spring": "Aquarel-Avets",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Aquarel",
        "spring": "Las Jaras",
        "place": "Herrera del Duque",
        "province": "Badajoz",
    },
    {
        "name": "Aquaservice Aquaservice Cogollos de Guadix",
        "spring": "Cogollos de Guadix",
        "place": "",
        "province": "Granada",
    },
    {"name": "Bastida", "spring": "Bastida", "place": "Alaró", "province": "Baleares"},
    {
        "name": "Betelu",
        "spring": "Ama-Iturri",
        "place": "Betelu",
        "province": "Navarra",
    },
    {
        "name": "Bezoya",
        "spring": "Bezoya",
        "place": "Ortigosa del Monte",
        "province": "Segovia",
    },
    {
        "name": "Bezoya Trescasas",
        "spring": "Bezoya Trescasas",
        "place": "Trescasas",
        "province": "Segovia",
    },
    {
        "name": "Binifaldó Font Des Pedregaret y Binifaldó",
        "spring": "Escorca",
        "place": "",
        "province": "Baleares",
    },
    {
        "name": "Borines",
        "spring": "Manantial La Victoria",
        "place": "Borines-Piloña",
        "province": "Asturias",
    },
    {
        "name": "Cabreiroá",
        "spring": "Cabreiroá",
        "place": "Verín",
        "province": "Ourense",
    },
    {
        "name": "Cabreiroá",
        "spring": "Cabreiroá 3",
        "place": "Verín",
        "province": "Ourense",
    },
    {
        "name": "Calabor",
        "spring": "Calabor",
        "place": "Pedralba de la Pradería",
        "province": "Zamora",
    },
    {
        "name": "Caldes de Bohi",
        "spring": "Font del Bou",
        "place": "Barruera",
        "province": "Lleida",
    },
    {
        "name": "Cantalar",
        "spring": "Cantalar",
        "place": "Moratalla",
        "province": "Murcia",
    },
    {
        "name": "Carrizal",
        "spring": "Carrizal",
        "place": "San Andrés del Rabanedo",
        "province": "León",
    },
    {
        "name": "Carrizal II",
        "spring": "Carrizal II",
        "place": "Cuadros",
        "province": "León",
    },
    {"name": "Cautiva", "spring": "Cautiva", "place": "Sarriá", "province": "Lugo"},
    {
        "name": "Corconte",
        "spring": "Balneario de Corconte",
        "place": "Valle de Valdebezana",
        "province": "Burgos",
    },
    {
        "name": "Cortes",
        "spring": "Penyagolosa",
        "place": "Cortes de Arenoso",
        "province": "Castellón",
    },
    {
        "name": "Don Pepe",
        "spring": "Montalvo V",
        "place": "Aldeatajada",
        "province": "Salamanca",
    },
    {
        "name": "El Cañar",
        "spring": "El Cañar",
        "place": "Jaraba",
        "province": "Zaragoza",
    },
    {
        "name": "El Portell, MP",
        "spring": "El Portell",
        "place": "Monserrat",
        "province": "Valencia",
    },
    {
        "name": "Eliqua",
        "spring": "Font d'Elca",
        "place": "Salem",
        "province": "Valencia",
    },
    {
        "name": "Eliqua 2",
        "spring": "Eliqua 2",
        "place": "Salem",
        "province": "Valencia",
    },
    {
        "name": "Estrella l",
        "spring": "Estrella l",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Estrella M",
        "spring": "Estrella M",
        "place": "Almazán",
        "province": "Soria",
    },
    {
        "name": "Estrella V",
        "spring": "Estrella V",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Fondetal",
        "spring": "Fondetal",
        "place": "Talarrubias",
        "province": "Badajoz",
    },
    {
        "name": "Fonsana",
        "spring": "Fonsana",
        "place": "La Cabrera",
        "province": "Madrid",
    },
    {
        "name": "Font Agudes",
        "spring": "Ballanes",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Font de Sa Senyora",
        "spring": "Font de Sa Senyora",
        "place": "Deià",
        "province": "Baleares",
    },
    {
        "name": "Font del Regàs",
        "spring": "Font del Regàs",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Font del Subirà",
        "spring": "El Subirà",
        "place": "Osor",
        "province": "Girona",
    },
    {
        "name": "Font des Teix",
        "spring": "Font des Teix",
        "place": "Bunyola",
        "province": "Baleares",
    },
    {
        "name": "Font Major",
        "spring": "Font Major",
        "place": "Escorca",
        "province": "Baleares",
    },
    {
        "name": "Font Natura",
        "spring": "Font Natura",
        "place": "Loja",
        "province": "Granada",
    },
    {
        "name": "Font Nova del Pla",
        "spring": "Font Nova del Pla",
        "place": "Santes Creus-Aiguamúrcia",
        "province": "Tarragona",
    },
    {
        "name": "Font S'Aritja",
        "spring": "Font S'Aritja",
        "place": "Bunyola",
        "province": "Baleares",
    },
    {
        "name": "Font Sol",
        "spring": "Aguas de Sierra",
        "place": "La Font de la Figuera",
        "province": "Valencia",
    },
    {
        "name": "Font Sorda Son Cocó",
        "spring": "Font Sorda-Son Cocó",
        "place": "Alaró",
        "province": "Baleares",
    },
    {
        "name": "Font Vella",
        "spring": "Font Vella Sacalm",
        "place": "Sant Hilari Sacalm",
        "province": "Girona",
    },
    {
        "name": "Font Vella",
        "spring": "Font Vella Sigüenza",
        "place": "Moratilla de Henares Sigüenza",
        "province": "Guadalajara",
    },
    {"name": "Fontarel", "spring": "El Pilar", "place": "Loja", "province": "Granada"},
    {
        "name": "Fontcristall",
        "spring": "Fontcristall",
        "place": "Ribes de Freser",
        "province": "Girona",
    },
    {
        "name": "Fontdalt",
        "spring": "Fontdalt",
        "place": "Tivissa",
        "province": "Tarragona",
    },
    {
        "name": "Fontdor",
        "spring": "Fontdor",
        "place": "Sant Hilari Sacalm",
        "province": "Girona",
    },
    {
        "name": "Fontecabras",
        "spring": "Fontecabras",
        "place": "Jaraba",
        "province": "Zaragoza",
    },
    {
        "name": "Fontecelta",
        "spring": "Fontecelta",
        "place": "Sarriá",
        "province": "Lugo",
    },
    {
        "name": "Fonteide",
        "spring": "Fonteide",
        "place": "La Orotava",
        "province": "Santa Cruz de Tenerife",
    },
    {
        "name": "Fontemilla",
        "spring": "Fontemilla Moratilla de Henares",
        "place": "",
        "province": "Sigüenza",
    },
    {
        "name": "Fontenova",
        "spring": "Fontenova",
        "place": "Verín",
        "province": "Ourense",
    },
    {"name": "Fonter", "spring": "Fonter", "place": "Amer", "province": "Girona"},
    {"name": "Fonter", "spring": "Palatín", "place": "Amer", "province": "Girona"},
    {
        "name": "Fonxesta",
        "spring": "Fonxesta",
        "place": "Vega de Anzuelos-Láncara",
        "province": "Lugo",
    },
    {
        "name": "Fuencisla",
        "spring": "Fuencisla",
        "place": "Requena",
        "province": "Valencia",
    },
    {
        "name": "Fuensanta",
        "spring": "Fuensanta de Buyeres",
        "place": "Nava",
        "province": "Asturias",
    },
    {
        "name": "Fuente del Val",
        "spring": "Fuente del Val 2",
        "place": "Mondariz",
        "province": "Pontevedra",
    },
    {
        "name": "Fuente en Segures",
        "spring": "Fuente en Segures",
        "place": "Benasal",
        "province": "Castellón",
    },
    {
        "name": "Fuente Madre",
        "spring": "Fuente Madre",
        "place": "Los Navalmorales",
        "province": "Toledo",
    },
    {
        "name": "Fuente Pinar",
        "spring": "Guadalvida",
        "place": "Villanueva del Arzobispo",
        "province": "Jaén",
    },
    {
        "name": "Fuente Primavera",
        "spring": "Fuente Primavera",
        "place": "Requena",
        "province": "Valencia",
    },
    {
        "name": "Fuentebruma",
        "spring": "Fuentebruma",
        "place": "Gáldar",
        "province": "Las Palmas",
    },
    {
        "name": "Fuentecilla",
        "spring": "Fuente del Fraile",
        "place": "Tarazona de la Mancha",
        "province": "Albacete",
    },
    {
        "name": "Fuentedueñas",
        "spring": "Fuente de la Higuerica",
        "place": "Mula",
        "province": "Murcia",
    },
    {
        "name": "Fuentelajara",
        "spring": "Fuentelajara",
        "place": "Belvis de la Jara",
        "province": "Toledo",
    },
    {
        "name": "FuenteLiviana",
        "spring": "FuenteLiviana",
        "place": "Huerta del Marquesado",
        "province": "Cuenca",
    },
    {
        "name": "Fuenteror",
        "spring": "Fuenteror",
        "place": "Teror",
        "province": "Las Palmas",
    },
    {
        "name": "Fuentevera",
        "spring": "Fuentevera",
        "place": "Calera y Chozas",
        "province": "Toledo",
    },
    {
        "name": "Galea",
        "spring": "Galea",
        "place": "Meres-Siero",
        "province": "Asturias",
    },
    {
        "name": "Imperial",
        "spring": "Imperial",
        "place": "Caldes de Malavella",
        "province": "Girona",
    },
    {
        "name": "Insalus",
        "spring": "Insalus",
        "place": "Lizartza",
        "province": "Guipúzcoa",
    },
    {
        "name": "L'Avellà",
        "spring": "Nuestra Señora de Avellà",
        "place": "Catí",
        "province": "Castellón",
    },
    {
        "name": "La Ideal I",
        "spring": "La Ideal I",
        "place": "Firgas",
        "province": "Las Palmas",
    },
    {
        "name": "La Ideal II",
        "spring": "La Ideal II (El Rapador)",
        "place": "Firgas",
        "province": "Las Palmas",
    },
    {"name": "La Paz", "spring": "La Paz", "place": "Marmolejo", "province": "Jaén"},
    {
        "name": "La Serreta",
        "spring": "La Serreta",
        "place": "La Font de la Figuera",
        "province": "Valencia",
    },
    {
        "name": "Lahoz",
        "spring": "La Hoz",
        "place": "Huerta del Marquesado",
        "province": "Cuenca",
    },
    {
        "name": "Landín",
        "spring": "Landín",
        "place": "Ponteareas",
        "province": "Pontevedra",
    },
    {
        "name": "Lanjarón con gas",
        "spring": "Fonte Forte",
        "place": "Lanjarón",
        "province": "Granada",
    },
    {
        "name": "Lanjarón Salud",
        "spring": "Salud",
        "place": "Lanjarón",
        "province": "Granada",
    },
    {
        "name": "Las Higueras",
        "spring": "Las Higueras",
        "place": "Valsequillo",
        "province": "Las Palmas",
    },
    {
        "name": "Lebanza",
        "spring": "La Cueva",
        "place": "San Salvador de Cantamuda",
        "province": "Palencia",
    },
    {
        "name": "Les Creus",
        "spring": "Les Creus",
        "place": "Maçanet de Cabrenys",
        "province": "Girona",
    },
    {
        "name": "Los Riscos",
        "spring": "Los Riscos de la Higüela",
        "place": "Alburquerque",
        "province": "Badajoz",
    },
    {"name": "Lunares", "spring": "Lunares", "place": "Jaraba", "province": "Zaragoza"},
    {
        "name": "Magma de Cabreiroá",
        "spring": "Cabreiroá 2",
        "place": "Verín",
        "province": "Ourense",
    },
    {
        "name": "Malavella",
        "spring": "Malavella",
        "place": "Caldes de Malavella",
        "province": "Girona",
    },
    {
        "name": "Manantial de Almedijar",
        "spring": "Fuente del Cañar",
        "place": "Partida del Cañar. Almedijar",
        "province": "Castellón",
    },
    {
        "name": "Manantial San Millán",
        "spring": "San Millán",
        "place": "Torrecilla en Cameros",
        "province": "La Rioja",
    },
    {
        "name": "Mondariz",
        "spring": "Mondariz IV",
        "place": "Mondariz-Balneario",
        "province": "Pontevedra",
    },
    {
        "name": "Monssalus",
        "spring": "Monssalus",
        "place": "Albuñan",
        "province": "Granada",
    },
    {
        "name": "Montepinos",
        "spring": "Montepinos",
        "place": "Almazán",
        "province": "Soria",
    },
    {"name": "Natura", "spring": "Natura", "place": "Los Villares", "province": "Jaén"},
    {
        "name": "Nature Montes de León",
        "spring": "Nature Montes de León",
        "place": "La Ribera de Folgoso",
        "province": "León",
    },
    {"name": "Neval", "spring": "Neval", "place": "Moratalla", "province": "Murcia"},
    {
        "name": "Numen Premium Water",
        "spring": "Numen",
        "place": "Villarubia de los Ojos",
        "province": "Ciudad Real",
    },
    {
        "name": "Orotana",
        "spring": "Orotana",
        "place": "Artana",
        "province": "Castellón",
    },
    {
        "name": "Panticosa",
        "spring": "San Agustín",
        "place": "Balneario de Panticosa",
        "province": "Huesca",
    },
    {
        "name": "Peñaclara",
        "spring": "Peñaclara",
        "place": "Torrecilla en Cameros",
        "province": "La Rioja",
    },
    {"name": "Pineo", "spring": "Pineo", "place": "Estamariu", "province": "Lleida"},
    {"name": "Pirinea", "spring": "Pirinea", "place": "Bisaurri", "province": "Huesca"},
    {
        "name": "Rocallaura",
        "spring": "Agua de Rocallaura",
        "place": "Vallbona de les Monges",
        "province": "Lleida",
    },
    {
        "name": "San Andrés",
        "spring": "San Andrés",
        "place": "San Andrés de Rabanedo",
        "province": "León",
    },
    {
        "name": "San Andrés II",
        "spring": "San Andrés II",
        "place": "Cuadros",
        "province": "León",
    },
    {
        "name": "San Antón II",
        "spring": "San Antón II",
        "place": "Firgas",
        "province": "Las Palmas",
    },
    {
        "name": "San Joaquín",
        "spring": "San Joaquín",
        "place": "Valdunciel",
        "province": "Salamanca",
    },
    {
        "name": "San Narciso",
        "spring": "San Narciso",
        "place": "Caldes de Malavella",
        "province": "Girona",
    },
    {
        "name": "San Vicente",
        "spring": "San Vicente",
        "place": "Lanjarón",
        "province": "Granada",
    },
    {
        "name": "Sant Aniol",
        "spring": "Sant Aniol",
        "place": "Sant Aniol de Finestres",
        "province": "Girona",
    },
    {
        "name": "Sant Hilari",
        "spring": "Sant Hilari",
        "place": "Arbúcies",
        "province": "Girona",
    },
    {
        "name": "Sanxinés",
        "spring": "Sanxinés",
        "place": "Bamio-Villagarcía de Arousa",
        "province": "Pontevedra",
    },
    {
        "name": "Sierra Bonela",
        "spring": "Casarabonela",
        "place": "Casarabonela",
        "province": "Málaga",
    },
    {
        "name": "Sierra de Cazorla",
        "spring": "Sierra Cazorla",
        "place": "Villanueva del Arzobispo",
        "province": "Jaén",
    },
    {
        "name": "Sierra de Mijas",
        "spring": "La Ermitica",
        "place": "Mijas",
        "province": "Málaga",
    },
    {
        "name": "Sierra de Segura",
        "spring": "Fuente Blanca",
        "place": "Villanueva del Arzobispo",
        "province": "Jaén",
    },
    {
        "name": "Sierra del Búho",
        "spring": "Sierra del Búho",
        "place": "Moratalla",
        "province": "Murcia",
    },
    {
        "name": "Sierra del Águila",
        "spring": "La Majuela",
        "place": "Cariñena",
        "province": "Zaragoza",
    },
    {
        "name": "Sierra Dúrcal",
        "spring": "Sierra Dúrcal",
        "place": "Dúrcal",
        "province": "Granada",
    },
    {
        "name": "Sierra Fría",
        "spring": "El Chumacero",
        "place": "Valencia de Alcántara",
        "province": "Cáceres",
    },
    {
        "name": "Sierra Natura",
        "spring": "Fuente del Arca",
        "place": "Beteta",
        "province": "Cuenca",
    },
    {
        "name": "Sierras de Jaén",
        "spring": "Sierras de Jaén",
        "place": "Los Villares",
        "province": "Jaén",
    },
    {
        "name": "Soceo",
        "spring": "Soceo",
        "place": "La Ribera de Folgoso",
        "province": "León",
    },
    {
        "name": "Solares",
        "spring": "Fuencaliente de Solares",
        "place": "Solares",
        "province": "Cantabria",
    },
    {
        "name": "Solán de Cabras",
        "spring": "Solán de Cabras",
        "place": "Beteta",
        "province": "Cuenca",
    },
    {
        "name": "Teleno",
        "spring": "Teleno",
        "place": "Palacios de la Valduerna",
        "province": "León",
    },
    {
        "name": "Valtorre",
        "spring": "Valtorre",
        "place": "Belvis de la Jara",
        "province": "Toledo",
    },
    {"name": "Veri", "spring": "Veri 1", "place": "Bisaurri", "province": "Huesca"},
    {
        "name": "Veri",
        "spring": "Veri 5",
        "place": "El Run-Castejón de Sos",
        "province": "Huesca",
    },
    {
        "name": "Versión AMN/8",
        "spring": "17/09/2018 Babilafuente",
        "place": "Antigua Fuente del Caño Babilafuente",
        "province": "Salamanca",
    },
    {
        "name": "Versión AMN/8",
        "spring": "17/09/2018 Fontboix",
        "place": "Font del Boix Barruera",
        "province": "Lleida",
    },
    {
        "name": "Versión AMN/8",
        "spring": "17/09/2018 Liviana",
        "place": "Eliqua Salem",
        "province": "Valencia",
    },
    {
        "name": "Versión AMN/8",
        "spring": "17/09/2018 Soceo II",
        "place": "Soceo II LA RIBERA DE FOLGOSO",
        "province": "León",
    },
    {
        "name": "Vichy Catalán",
        "spring": "Vichy Catalán",
        "place": "Caldes de Malavella",
        "province": "Girona",
    },
    {
        "name": "Viladrau",
        "spring": "Fontalegre",
        "place": "Viladrau",
        "province": "Girona",
    },
    {
        "name": "Vilas del Turbón",
        "spring": "Vilas",
        "place": "Torrelaribera",
        "province": "Huesca",
    },
    {
        "name": "Virgen del Camino",
        "spring": "Virgen del Camino",
        "place": "San Miguel del Camino",
        "province": "León",
    },
]
