"""Seed catalog: well-known Spanish bottled waters with label data.

Values are approximate transcriptions of real labels (mg/L); every entry is
`verified=False` until someone checks it against a physical bottle. Sources:
manufacturer sites and label photos. Provenance (spring/province) cross-checked
with the AESAN recognised-waters list.
"""

SEED_WATERS = [
    {
        "id": "solan-de-cabras",
        "name": "Solán de Cabras",
        "brand": "Solán de Cabras",
        "spring": "Solán de Cabras",
        "province": "Cuenca",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 261,
            "bicarbonates": 284.8,
            "chlorides": 7.8,
            "sulfates": 21.3,
            "calcium": 59.5,
            "magnesium": 25.7,
            "sodium": 5.2,
            "potassium": 1.0,
            "ph": 7.4,
        },
    },
    {
        "id": "lanjaron",
        "name": "Lanjarón",
        "brand": "Lanjarón",
        "spring": "Fuente Salud",
        "province": "Granada",
        "community": "Andalucía",
        "minerals": {
            "tds": 205,
            "bicarbonates": 111,
            "chlorides": 10.1,
            "sulfates": 39.1,
            "calcium": 32.2,
            "magnesium": 11.6,
            "sodium": 8.5,
            "potassium": 1.2,
            "ph": 7.6,
        },
    },
    {
        "id": "bezoya",
        "name": "Bezoya",
        "brand": "Bezoya",
        "spring": "Bezoya",
        "province": "Segovia",
        "community": "Castilla y León",
        "minerals": {
            "tds": 27,
            "bicarbonates": 6.1,
            "chlorides": 0.9,
            "sulfates": 5.0,
            "calcium": 2.4,
            "magnesium": 0.7,
            "sodium": 1.2,
            "silica": 7.0,
            "ph": 6.1,
        },
    },
    {
        "id": "font-vella",
        "name": "Font Vella",
        "brand": "Font Vella",
        "spring": "Sant Hilari Sacalm",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 197,
            "bicarbonates": 137,
            "chlorides": 21.0,
            "sulfates": 9.3,
            "calcium": 40.1,
            "magnesium": 7.6,
            "sodium": 12.0,
            "potassium": 1.2,
            "silica": 15.0,
            "ph": 7.3,
        },
    },
    {
        "id": "vichy-catalan",
        "name": "Vichy Catalán",
        "brand": "Vichy Catalán",
        "spring": "Vichy Catalán",
        "province": "Girona",
        "community": "Cataluña",
        "sparkling": True,
        "minerals": {
            "tds": 3052,
            "bicarbonates": 2081,
            "chlorides": 601,
            "sulfates": 47.5,
            "calcium": 14.2,
            "magnesium": 9.0,
            "sodium": 1110,
            "potassium": 48.0,
            "ph": 6.8,
        },
    },
    {
        "id": "mondariz",
        "name": "Mondariz",
        "brand": "Mondariz",
        "spring": "Fuente del Val",
        "province": "Pontevedra",
        "community": "Galicia",
        "minerals": {
            "tds": 197,
            "bicarbonates": 133,
            "chlorides": 12.4,
            "sulfates": 2.0,
            "calcium": 25.8,
            "magnesium": 7.4,
            "sodium": 11.6,
            "potassium": 2.4,
            "silica": 24.0,
            "ph": 7.0,
        },
    },
    {
        "id": "cabreiroa",
        "name": "Cabreiroá",
        "brand": "Cabreiroá",
        "spring": "Cabreiroá",
        "province": "Ourense",
        "community": "Galicia",
        "minerals": {
            "tds": 253,
            "bicarbonates": 187,
            "chlorides": 15.0,
            "sulfates": 2.5,
            "calcium": 8.0,
            "magnesium": 4.7,
            "sodium": 44.1,
            "potassium": 5.5,
            "silica": 41.0,
            "ph": 6.9,
        },
    },
    {
        "id": "veri",
        "name": "Veri",
        "brand": "Veri",
        "spring": "Veri (Pirineo de Huesca)",
        "province": "Huesca",
        "community": "Aragón",
        "minerals": {
            "tds": 183,
            "bicarbonates": 138,
            "chlorides": 1.0,
            "sulfates": 22.0,
            "calcium": 47.8,
            "magnesium": 8.1,
            "sodium": 1.4,
            "ph": 7.8,
        },
    },
    {
        "id": "agua-de-cuevas",
        "name": "Agua de Cuevas",
        "brand": "Agua de Cuevas",
        "spring": "Cuevas (Felechosa)",
        "province": "Asturias",
        "community": "Asturias",
        "minerals": {
            "tds": 68,
            "bicarbonates": 65.0,
            "chlorides": 1.5,
            "sulfates": 3.5,
            "calcium": 20.1,
            "magnesium": 1.1,
            "sodium": 2.5,
            "ph": 7.5,
        },
    },
    {
        "id": "aquadeus",
        "name": "Aquadeus",
        "brand": "Aquadeus",
        "spring": "Fuente Arquillo",
        "province": "Albacete",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 291,
            "bicarbonates": 262,
            "chlorides": 8.0,
            "sulfates": 30.0,
            "calcium": 63.0,
            "magnesium": 22.0,
            "sodium": 6.0,
            "ph": 7.5,
        },
    },
    {
        "id": "sierra-cazorla",
        "name": "Sierra Cazorla",
        "brand": "Sierra Cazorla",
        "spring": "Manantial del Tobazo",
        "province": "Jaén",
        "community": "Andalucía",
        "minerals": {
            "tds": 325,
            "bicarbonates": 320,
            "chlorides": 5.0,
            "sulfates": 15.0,
            "calcium": 78.0,
            "magnesium": 17.0,
            "sodium": 3.5,
            "ph": 7.6,
        },
    },
    {
        "id": "fuente-liviana",
        "name": "Fuente Liviana",
        "brand": "Fuente Liviana",
        "spring": "Fuente Liviana (Serranía de Cuenca)",
        "province": "Cuenca",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 285,
            "bicarbonates": 255,
            "chlorides": 4.0,
            "sulfates": 25.0,
            "calcium": 75.0,
            "magnesium": 16.0,
            "sodium": 2.5,
            "ph": 7.5,
        },
    },
    {
        "id": "solares",
        "name": "Solares",
        "brand": "Solares",
        "spring": "Fuencaliente",
        "province": "Cantabria",
        "community": "Cantabria",
        "minerals": {
            "tds": 322,
            "bicarbonates": 205,
            "chlorides": 60.0,
            "sulfates": 30.0,
            "calcium": 51.0,
            "magnesium": 15.0,
            "sodium": 40.0,
            "ph": 7.5,
        },
    },
    {
        "id": "fuensanta",
        "name": "Fuensanta",
        "brand": "Fuensanta",
        "spring": "Fuensanta (Nava)",
        "province": "Asturias",
        "community": "Asturias",
        "minerals": {
            "tds": 205,
            "bicarbonates": 148,
            "chlorides": 8.0,
            "sulfates": 15.0,
            "calcium": 42.0,
            "magnesium": 8.5,
            "sodium": 6.0,
            "ph": 7.4,
        },
    },
    {
        "id": "aigua-de-ribes",
        "name": "Aigua de Ribes",
        "brand": "Aigua de Ribes",
        "spring": "Ribes de Freser",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 208,
            "bicarbonates": 180,
            "chlorides": 3.0,
            "sulfates": 10.0,
            "calcium": 55.0,
            "magnesium": 6.0,
            "sodium": 3.0,
            "ph": 7.4,
        },
    },
]
