"""Seed catalog: well-known Spanish bottled waters with label data.

Values are approximate transcriptions of real labels (mg/L); every entry is
`verified=False` until someone checks it against a physical bottle. Sources:
manufacturer sites and label photos. Provenance (spring/province) cross-checked
with the AESAN recognised-waters list.
"""

SEED_WATERS = [
    {
        "id": "solan-de-cabras",
        "name": "Solán de Cabras",
        "brand": "Solán de Cabras",
        "spring": "Solán de Cabras (Beteta)",
        "province": "Cuenca",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 261,
            "bicarbonates": 284.8,
            "chlorides": 7.8,
            "sulfates": 21.3,
            "calcium": 59.5,
            "magnesium": 25.7,
            "sodium": 5.2,
            "potassium": 1.0,
            "ph": 7.4,
        },
    },
    {
        "id": "lanjaron",
        "name": "Lanjarón",
        "brand": "Lanjarón",
        "spring": "Manantial Salud",
        "province": "Granada",
        "community": "Andalucía",
        # HCO3/Ca/Mg/Na confirmed from a bottle label (CNTA 2023 analysis);
        # the label prints nothing else, so the rest stays approximate and
        # the water remains unverified.
        "photo_url": "https://storage.googleapis.com/be-water-photos/lanjaron.jpg",
        "label_photo_url": "https://storage.googleapis.com/be-water-photos"
        "/originals/lanjaron.jpg",
        "verified_fields": ["bicarbonates", "calcium", "magnesium", "sodium"],
        "minerals": {
            "tds": 205,
            "bicarbonates": 105.0,
            "chlorides": 10.1,
            "sulfates": 39.1,
            "calcium": 25.9,
            "magnesium": 9.0,
            "sodium": 5.2,
            "potassium": 1.2,
            "ph": 7.6,
        },
    },
    {
        "id": "bezoya",
        "name": "Bezoya",
        "brand": "Bezoya",
        "spring": "Bezoya",
        "province": "Segovia",
        "community": "Castilla y León",
        "minerals": {
            "tds": 27,
            "bicarbonates": 6.1,
            "chlorides": 0.9,
            "sulfates": 5.0,
            "calcium": 2.4,
            "magnesium": 0.7,
            "sodium": 1.2,
            "silica": 7.0,
            "ph": 6.1,
        },
    },
    {
        "id": "font-vella",
        "name": "Font Vella",
        "brand": "Font Vella",
        "spring": "Sant Hilari Sacalm",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 197,
            "bicarbonates": 137,
            "chlorides": 21.0,
            "sulfates": 9.3,
            "calcium": 40.1,
            "magnesium": 7.6,
            "sodium": 12.0,
            "potassium": 1.2,
            "silica": 15.0,
            "ph": 7.3,
        },
    },
    {
        "id": "vichy-catalan",
        "name": "Vichy Catalán",
        "brand": "Vichy Catalán",
        "spring": "Vichy Catalán",
        "province": "Girona",
        "community": "Cataluña",
        "sparkling": True,
        "minerals": {
            "tds": 3052,
            "bicarbonates": 2081,
            "chlorides": 601,
            "sulfates": 47.5,
            "calcium": 14.2,
            "magnesium": 9.0,
            "sodium": 1110,
            "potassium": 48.0,
            "ph": 6.8,
        },
    },
    {
        "id": "mondariz",
        "name": "Mondariz",
        "brand": "Mondariz",
        "spring": "Fuente del Val",
        "province": "Pontevedra",
        "community": "Galicia",
        "minerals": {
            "tds": 197,
            "bicarbonates": 133,
            "chlorides": 12.4,
            "sulfates": 2.0,
            "calcium": 25.8,
            "magnesium": 7.4,
            "sodium": 11.6,
            "potassium": 2.4,
            "silica": 24.0,
            "ph": 7.0,
        },
    },
    {
        "id": "cabreiroa",
        "name": "Cabreiroá",
        "brand": "Cabreiroá",
        "spring": "Cabreiroá",
        "province": "Ourense",
        "community": "Galicia",
        "minerals": {
            "tds": 253,
            "bicarbonates": 187,
            "chlorides": 15.0,
            "sulfates": 2.5,
            "calcium": 8.0,
            "magnesium": 4.7,
            "sodium": 44.1,
            "potassium": 5.5,
            "silica": 41.0,
            "ph": 6.9,
        },
    },
    {
        "id": "veri",
        "name": "Veri",
        "brand": "Veri",
        "spring": "Veri (Pirineo de Huesca)",
        "province": "Huesca",
        "community": "Aragón",
        "minerals": {
            "tds": 183,
            "bicarbonates": 138,
            "chlorides": 1.0,
            "sulfates": 22.0,
            "calcium": 47.8,
            "magnesium": 8.1,
            "sodium": 1.4,
            "ph": 7.8,
        },
    },
    {
        "id": "agua-de-cuevas",
        "name": "Agua de Cuevas",
        "brand": "Agua de Cuevas",
        "spring": "Cuevas (Felechosa)",
        "province": "Asturias",
        "community": "Asturias",
        "minerals": {
            "tds": 68,
            "bicarbonates": 65.0,
            "chlorides": 1.5,
            "sulfates": 3.5,
            "calcium": 20.1,
            "magnesium": 1.1,
            "sodium": 2.5,
            "ph": 7.5,
        },
    },
    {
        "id": "aquadeus",
        "name": "Aquadeus",
        "brand": "Aquadeus",
        "spring": "Fuente Arquillo (Masegoso)",
        "province": "Albacete",
        "community": "Castilla-La Mancha",
        # Label-verified 2026-07-18 (bottle photo).
        "verified": True,
        "photo_url": "https://storage.googleapis.com/be-water-photos/aquadeus.jpg",
        "label_photo_url": "https://storage.googleapis.com/be-water-photos"
        "/originals/aquadeus.jpg",
        "minerals": {
            "tds": 307,
            "bicarbonates": 336,
            "chlorides": 6.3,
            "sulfates": 15.1,
            "calcium": 86.2,
            "magnesium": 33.0,
            "sodium": 3.6,
            "potassium": 1.1,
            "ph": 7.7,
        },
    },
    {
        "id": "sierra-cazorla",
        "name": "Sierra Cazorla",
        "brand": "Sierra Cazorla",
        "spring": "Manantial del Tobazo",
        "province": "Jaén",
        "community": "Andalucía",
        "minerals": {
            "tds": 325,
            "bicarbonates": 320,
            "chlorides": 5.0,
            "sulfates": 15.0,
            "calcium": 78.0,
            "magnesium": 17.0,
            "sodium": 3.5,
            "ph": 7.6,
        },
    },
    {
        "id": "fuente-liviana",
        "name": "Fuente Liviana",
        "brand": "Fuente Liviana",
        "spring": "Fuente Liviana (Serranía de Cuenca)",
        "province": "Cuenca",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 285,
            "bicarbonates": 255,
            "chlorides": 4.0,
            "sulfates": 25.0,
            "calcium": 75.0,
            "magnesium": 16.0,
            "sodium": 2.5,
            "ph": 7.5,
        },
    },
    {
        "id": "solares",
        "name": "Solares",
        "brand": "Solares",
        "spring": "Fuencaliente",
        "province": "Cantabria",
        "community": "Cantabria",
        "minerals": {
            "tds": 322,
            "bicarbonates": 205,
            "chlorides": 60.0,
            "sulfates": 30.0,
            "calcium": 51.0,
            "magnesium": 15.0,
            "sodium": 40.0,
            "ph": 7.5,
        },
    },
    {
        "id": "fuensanta",
        "name": "Fuensanta",
        "brand": "Fuensanta",
        "spring": "Fuensanta (Nava)",
        "province": "Asturias",
        "community": "Asturias",
        "minerals": {
            "tds": 205,
            "bicarbonates": 148,
            "chlorides": 8.0,
            "sulfates": 15.0,
            "calcium": 42.0,
            "magnesium": 8.5,
            "sodium": 6.0,
            "ph": 7.4,
        },
    },
    {
        "id": "aigua-de-ribes",
        "name": "Aigua de Ribes",
        "brand": "Aigua de Ribes",
        "spring": "Ribes de Freser",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 208,
            "bicarbonates": 180,
            "chlorides": 3.0,
            "sulfates": 10.0,
            "calcium": 55.0,
            "magnesium": 6.0,
            "sodium": 3.0,
            "ph": 7.4,
        },
    },
    {
        "id": "viladrau",
        "name": "Viladrau",
        "brand": "Viladrau (Nestlé Aquarel)",
        "spring": "Viladrau (Montseny)",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 118,
            "bicarbonates": 66.0,
            "chlorides": 11.0,
            "sulfates": 8.0,
            "calcium": 20.0,
            "magnesium": 3.5,
            "sodium": 7.5,
            "silica": 15.0,
            "ph": 6.9,
        },
    },
    {
        "id": "sant-aniol",
        "name": "Sant Aniol",
        "brand": "Sant Aniol",
        "spring": "Sant Aniol de Finestres",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 226,
            "bicarbonates": 195,
            "chlorides": 6.0,
            "sulfates": 8.0,
            "calcium": 55.0,
            "magnesium": 8.0,
            "sodium": 5.5,
            "ph": 7.3,
        },
    },
    {
        "id": "agua-de-benassal",
        "name": "Agua de Benassal",
        "brand": "Agua de Benassal",
        "spring": "Font d'en Segures",
        "province": "Castellón",
        "community": "Comunidad Valenciana",
        "minerals": {
            "tds": 370,
            "bicarbonates": 300,
            "chlorides": 12.0,
            "sulfates": 30.0,
            "calcium": 85.0,
            "magnesium": 25.0,
            "sodium": 6.0,
            "ph": 7.4,
        },
    },
    {
        "id": "bronchales",
        "name": "Bronchales",
        "brand": "Bronchales",
        "spring": "Fuente del Canto",
        "province": "Teruel",
        "community": "Aragón",
        "minerals": {
            "tds": 44,
            "bicarbonates": 21.0,
            "chlorides": 1.5,
            "sulfates": 4.0,
            "calcium": 6.0,
            "magnesium": 1.5,
            "sodium": 4.0,
            "silica": 15.0,
            "ph": 6.5,
        },
    },
    {
        "id": "insalus",
        "name": "Insalus",
        "brand": "Insalus",
        "spring": "Insalus (Lizartza)",
        "province": "Guipúzcoa",
        "community": "País Vasco",
        "minerals": {
            "tds": 505,
            "bicarbonates": 285,
            "chlorides": 10.0,
            "sulfates": 120.0,
            "calcium": 130.0,
            "magnesium": 15.0,
            "sodium": 7.0,
            "ph": 7.3,
        },
    },
    {
        "id": "fuente-primavera",
        "name": "Fuente Primavera",
        "brand": "Fuente Primavera",
        "spring": "San Antonio de Requena",
        "province": "Valencia",
        "community": "Comunidad Valenciana",
        "minerals": {
            "tds": 330,
            "bicarbonates": 290,
            "chlorides": 8.0,
            "sulfates": 25.0,
            "calcium": 85.0,
            "magnesium": 20.0,
            "sodium": 5.0,
            "ph": 7.5,
        },
    },
    {
        "id": "penaclara",
        "name": "Peñaclara",
        "brand": "Peñaclara",
        "spring": "Peñaclara (Torrecilla en Cameros)",
        "province": "La Rioja",
        "community": "La Rioja",
        "minerals": {
            "tds": 490,
            "bicarbonates": 220,
            "chlorides": 8.0,
            "sulfates": 180.0,
            "calcium": 120.0,
            "magnesium": 20.0,
            "sodium": 5.0,
            "ph": 7.4,
        },
    },
    {
        "id": "sousas",
        "name": "Sousas",
        "brand": "Sousas",
        "spring": "Sousas (Verín)",
        "province": "Ourense",
        "community": "Galicia",
        "minerals": {
            "tds": 180,
            "bicarbonates": 120,
            "chlorides": 9.0,
            "sulfates": 3.0,
            "calcium": 12.0,
            "magnesium": 4.0,
            "sodium": 30.0,
            "silica": 30.0,
            "ph": 6.8,
        },
    },
    {
        "id": "valtorre",
        "name": "Valtorre",
        "brand": "Valtorre",
        "spring": "Valtorre (Sierra de San Vicente)",
        "province": "Toledo",
        "community": "Castilla-La Mancha",
        # Label-verified 2026-07-18 (bottle photo). Minero-medicinal, BOE 1972.
        "verified": True,
        "photo_url": "https://storage.googleapis.com/be-water-photos/valtorre.jpg",
        "label_photo_url": "https://storage.googleapis.com/be-water-photos"
        "/originals/valtorre.jpg",
        "minerals": {
            "tds": 235,
            "bicarbonates": 151.8,
            "chlorides": 43.8,
            "sulfates": 23.2,
            "calcium": 16.9,
            "magnesium": 18.0,
            "sodium": 35.3,
            "silica": 13.6,
        },
    },
    {
        "id": "font-del-regas",
        "name": "Font del Regàs",
        "brand": "Font del Regàs",
        "spring": "Font del Regàs (Arbúcies, Montseny)",
        "province": "Girona",
        "community": "Cataluña",
        # Values from the manufacturer's official label sheet (PDF).
        "minerals": {
            "tds": 167,
            "bicarbonates": 111.0,
            "chlorides": 18.9,
            "sulfates": 9.2,
            "calcium": 26.6,
            "magnesium": 1.3,
            "sodium": 28.2,
            "silica": 21.6,
        },
    },
    {
        "id": "aquabona",
        "name": "Aquabona",
        "brand": "Aquabona (Coca-Cola)",
        "spring": "Fuen Mayor",
        "province": "Teruel",
        "community": "Aragón",
        "minerals": {
            "tds": 332,
            "bicarbonates": 311.0,
            "chlorides": 4.9,
            "sulfates": 15.3,
            "calcium": 98.2,
            "magnesium": 10.9,
            "sodium": 3.4,
        },
    },
    {
        "id": "carrefour-sierra-de-segura",
        "name": "Carrefour Sierra de Segura",
        "brand": "Carrefour",
        "spring": "Fuenteblanca (Sierra de Segura)",
        "province": "Jaén",
        "community": "Andalucía",
        "minerals": {
            "tds": 254,
            "bicarbonates": 251.0,
            "chlorides": 4.1,
            "sulfates": 9.8,
            "calcium": 71.3,
            "magnesium": 18.2,
            "sodium": 2.1,
        },
    },
    {
        "id": "naturis-lidl",
        "name": "Naturis (Lidl)",
        "brand": "Lidl",
        "spring": "Fuente Arquillo (Masegoso)",
        "province": "Albacete",
        "community": "Castilla-La Mancha",
        # Same spring as Aquadeus — composition mirrors its label-verified
        # values until someone photographs a Naturis bottle.
        "minerals": {
            "tds": 307,
            "bicarbonates": 336,
            "chlorides": 6.3,
            "sulfates": 15.1,
            "calcium": 86.2,
            "magnesium": 33.0,
            "sodium": 3.6,
            "potassium": 1.1,
            "ph": 7.7,
        },
    },
    {
        "id": "la-majuela",
        "name": "La Majuela (Dia)",
        "brand": "Dia",
        "spring": "La Majuela (Cariñena)",
        "province": "Zaragoza",
        "community": "Aragón",
        # Values reported from a same-spring label; only those four fields.
        "minerals": {
            "tds": 320,
            "bicarbonates": 242.0,
            "calcium": 79.7,
            "sodium": 18.2,
        },
    },
    {
        "id": "malavella",
        "name": "Vichy Malavella",
        "brand": "Malavella",
        "spring": "Malavella (Caldes de Malavella)",
        "province": "Girona",
        "community": "Cataluña",
        "sparkling": True,
        "minerals": {
            "tds": 2811,
            "bicarbonates": 2135,
            "chlorides": 570,
            "sulfates": 44.0,
            "calcium": 55.0,
            "magnesium": 13.0,
            "sodium": 1090,
            "potassium": 45.0,
            "ph": 6.9,
        },
    },
    {
        "id": "font-d-or",
        "name": "Font d'Or",
        "brand": "Font d'Or",
        "spring": "Font d'Or (Sant Hilari Sacalm)",
        "province": "Girona",
        "community": "Cataluña",
        "minerals": {
            "tds": 185,
            "bicarbonates": 125,
            "chlorides": 15.0,
            "sulfates": 12.0,
            "calcium": 35.0,
            "magnesium": 8.0,
            "sodium": 11.0,
            "silica": 18.0,
            "ph": 7.1,
        },
    },
    {
        "id": "fondetal",
        "name": "Fondetal",
        "brand": "Fondetal",
        "spring": "Fondetal (Hormigos)",
        "province": "Toledo",
        "community": "Castilla-La Mancha",
        "minerals": {
            "tds": 37,
            "bicarbonates": 15.0,
            "chlorides": 3.5,
            "sulfates": 3.0,
            "calcium": 3.0,
            "magnesium": 1.2,
            "sodium": 4.5,
            "silica": 12.0,
            "ph": 6.3,
        },
    },
    {
        "id": "fontecabras",
        "name": "Fontecabras",
        "brand": "Fontecabras",
        "spring": "Fontecabras (Jaraba)",
        "province": "Zaragoza",
        "community": "Aragón",
        "minerals": {
            "tds": 780,
            "bicarbonates": 320,
            "chlorides": 60.0,
            "sulfates": 250.0,
            "calcium": 120.0,
            "magnesium": 40.0,
            "sodium": 45.0,
            "ph": 7.3,
        },
    },
    {
        "id": "lunares",
        "name": "Lunares",
        "brand": "Lunares",
        "spring": "Lunares (Jaraba)",
        "province": "Zaragoza",
        "community": "Aragón",
        "minerals": {
            "tds": 950,
            "bicarbonates": 340,
            "chlorides": 75.0,
            "sulfates": 330.0,
            "calcium": 150.0,
            "magnesium": 50.0,
            "sodium": 55.0,
            "ph": 7.2,
        },
    },
    {
        "id": "anavieja",
        "name": "Añavieja",
        "brand": "Añavieja",
        "spring": "Añavieja (Castilruiz)",
        "province": "Soria",
        "community": "Castilla y León",
        "minerals": {
            "tds": 1300,
            "bicarbonates": 250,
            "chlorides": 45.0,
            "sulfates": 650.0,
            "calcium": 250.0,
            "magnesium": 70.0,
            "sodium": 30.0,
            "ph": 7.3,
        },
    },
    {
        "id": "corconte",
        "name": "Corconte",
        "brand": "Corconte",
        "spring": "Fuente del Balneario de Corconte",
        "province": "Burgos",
        "community": "Castilla y León",
        "minerals": {
            "tds": 560,
            "bicarbonates": 310,
            "chlorides": 90.0,
            "sulfates": 25.0,
            "calcium": 20.0,
            "magnesium": 5.0,
            "sodium": 160.0,
            "ph": 7.0,
        },
    },
    {
        "id": "alzola",
        "name": "Alzola",
        "brand": "Alzola Basque Water",
        "spring": "Alzola (Elgoibar)",
        "province": "Guipúzcoa",
        "community": "País Vasco",
        "minerals": {
            "tds": 570,
            "bicarbonates": 290,
            "chlorides": 105.0,
            "sulfates": 30.0,
            "calcium": 45.0,
            "magnesium": 10.0,
            "sodium": 115.0,
            "ph": 7.5,
        },
    },
    {
        "id": "panticosa",
        "name": "Agua de Panticosa",
        "brand": "Panticosa",
        "spring": "Balneario de Panticosa (Pirineo)",
        "province": "Huesca",
        "community": "Aragón",
        "minerals": {
            "tds": 44,
            "bicarbonates": 22.0,
            "chlorides": 1.2,
            "sulfates": 8.0,
            "calcium": 7.0,
            "magnesium": 0.8,
            "sodium": 3.5,
            "silica": 14.0,
            "ph": 6.7,
        },
    },
    {
        "id": "bejis",
        "name": "Agua de Bejís",
        "brand": "Bejís",
        "spring": "Los Cloticos (Bejís)",
        "province": "Castellón",
        "community": "Comunidad Valenciana",
        "minerals": {
            "tds": 260,
            "bicarbonates": 230,
            "chlorides": 9.0,
            "sulfates": 20.0,
            "calcium": 65.0,
            "magnesium": 12.0,
            "sodium": 5.0,
            "ph": 7.4,
        },
    },
    {
        "id": "alhama",
        "name": "Aguavida Alhama",
        "brand": "Aguavida",
        "spring": "Alhama de Aragón",
        "province": "Zaragoza",
        "community": "Aragón",
        "minerals": {
            "tds": 480,
            "bicarbonates": 210,
            "chlorides": 45.0,
            "sulfates": 130.0,
            "calcium": 95.0,
            "magnesium": 25.0,
            "sodium": 25.0,
            "ph": 7.3,
        },
    },
]
